[build-system]
requires = ["setuptools>=58.0"]
build-backend = "setuptools.build_meta"

[project]
name = "skypilot"
version = "0.0.0"
authors = []
description = "An intercloud broker above the clouds"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
]

[project.urls]
"Homepage" = "https://sky-proj-sky.readthedocs-hosted.com/en/latest/"
"Bug Tracker" = "https://github.com/sky-proj/sky/issues"

[tool.yapf]
based_on_style = "google"
allow_split_before_dict_value = false
